ERP/Controllers/AccController.cs
using ERP.Models;
using ERP.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class AccController : Controller
    {
        // GET: Acc
        ErpDB db = new ErpDB();
        public ActionResult Index()
        {
            return View();
        }
        //public JsonResult expfunc(DateTime s , DateTime e)
        //{
        //    var query = db.ex(s,e)
        //    .Select(p => new { p.expname, p.expval });
        //    return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        //}
        //public JsonResult incomfunc(DateTime s, DateTime e)
        //{
        //    var query = db.incom(s, e)
        //    .Select(p => new { p.ItmName, p.totval });
        //    return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        //}
    }
}

ERP/Controllers/ProController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ERP.Models;
using System.IO;
using System.Web.Mvc.Async;
using System.Web.Mvc;
using ERP.Security;

namespace ERP.Controllers
{

    public class ProController : Controller
    {
        ErpDB db = new ErpDB();
        // GET: Pro
        public ActionResult Index()
        {
            return View();
        }
        // GET: cpy
        public ActionResult Cpy()
        {
            ViewBag.activity = new SelectList(db.CActivity.Where(x => x.IsActive == true), "ID", "ActivityName");
            return View();
        }
        public ActionResult Calendar()
        {
            return View();
        }
        // GET: prolist
        public ActionResult Prolist()
        {
            ViewBag.tpro = new SelectList(db.TPro.Where(x => x.IsActive == true), "ID", "TName");
            return View();
        }
        // Get : Gallery
        public ActionResult Gallerie()
        {
            var d = db.ArchPro.ToList();
            return View(d);
        }
        // Get : RPseven
        public ActionResult RPseven()
        {
            
            return View();
        }
        public ActionResult Adpro()
        {
            ViewBag.comfk = new SelectList(db.Company.Where(x => x.IsActive == true), "ID", "CompanyName");
            ViewBag.kprofk = new SelectList(db.KPro.Where(x => x.IsActive == true), "ID", "KName");
            ViewBag.purnamefk = new SelectList(db.PurType.Where(x => x.IsActive == true), "ID", "PurName");
            ViewBag.Galery = new SelectList(db.Gallary.Where(x => x.IsActive == true), "ID", "GallaryName");
            return View();
        }
        public ActionResult TechPro()
        {
            ViewBag.Galery = new SelectList(db.Gallary.Where(x => x.IsActive == true), "ID", "GallaryName");
            return View();
        }
        public ActionResult Garch()
        {
            return View();
        }
        public JsonResult tbGallery()
        {
            var query = db.Gallary.Where(x => x.IsActive == true).Select(x => new {x.ID , x.GallaryName ,x.ArchPro.Count }) ;
            return Json(new {aaData = query },JsonRequestBehavior.AllowGet);
        }
        public JsonResult adnpro(string proname,DateTime? fdate,DateTime? sdate,DateTime? tdate,DateTime? declaredate, decimal? totalval,int? kprofk, int? purnamefk, int cby)
        {
            ProList pl = new ProList();
            pl.ProName = proname;
            pl.TotalVal = totalval ?? 0;
            pl.KProFK = kprofk;
            pl.PurNameFK = purnamefk;
            pl.FirstAccepteDate = fdate;
            pl.SecandAccepteDate = sdate;
            pl.ThirdAceepteDate = tdate;
            pl.CreateBy = cby;
            pl.CreateDate = DateTime.Now;
            pl.IsActive = true;
            pl.Posted = 1;
            pl.ProStop = false;
            db.ProList.Add(pl);
            db.SaveChanges();
            return Json(new { Success = true, Message = " تم إضافة المشروع بنجاح" }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult adeditpro(int id,DateTime? fdate,DateTime?  sdate,DateTime? tdate, DateTime? declaredate ,decimal? totalval, int? kprofk, int? purnamefk)
        {

            var m = db.ProList.Where(x => x.ID == id).SingleOrDefault();
            m.KProFK = kprofk ?? m.KProFK;
            m.PurNameFK = purnamefk ?? m.PurNameFK;
            m.FirstAccepteDate = fdate ?? m.FirstAccepteDate;
            m.SecandAccepteDate = sdate ?? m.SecandAccepteDate;
            m.ThirdAceepteDate = tdate ?? m.ThirdAceepteDate;
            m.DeclareDate = declaredate ?? m.DeclareDate;
            m.TotalVal = totalval ?? m.TotalVal;
            db.SaveChanges();

            return Json(new { Success = true , Message = " تم التعديل البيانات بنجاح" }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbcpydef()
        {
            ErpDB db = new ErpDB();
            var query = db.Company.Where(z => z.IsActive == true)
            .Select(p => new { p.ID, p.CompanyName, p.ProList.Count });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbTProdef()
        {
            ErpDB db = new ErpDB();
            var query = db.TPro.Where(z => z.IsActive == true)
            .Select(p => new { p.ID, p.TName });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbprolistdef()
        {
            var query = db.ProList.Where(z => z.IsActive == true && z.Posted == 1 && z.ProStop == false)
                .Select(x => new { x.ID, x.ProName, x.TotalVal, x.KPro.TPro.TName, x.KPro.KName, x.PurType.PurName , x.FirstAccepteDate , x.SecandAccepteDate , x.ThirdAceepteDate , x.DeclareDate });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbprostate()
        {
            var query = db.ProList.Where(z => z.IsActive == true && z.ProStop == false)
                .Select(x => new { x.ID, x.ProName, x.PostList.PostedName , x.ExpForNow   });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbprofixstate()
        {
            var query = db.ProList.Where(z => z.IsActive == true && z.ProStop == true)
                .Select(x => new { x.ID, x.ProName, x.PostList.PostedName });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbtechprolistdef()
        {
            var query = db.ProList.Where(z => z.IsActive == true && z.Posted == 2 && z.ProStop == false)
                .Select(x => new { x.ID, x.ProName,x.TotalVal, x.FirstAccepteDate , x.SecandAccepteDate ,x.ThirdAceepteDate ,x.DeclareDate , x.OpnTechDate , x.SetTechDate });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbfinprolistdef()
        {
            var query = db.ProList.Where(z => z.IsActive == true && z.Posted == 3 && z.ProStop == false)
                .Select(x => new { x.ID, x.ProName, x.TotalVal,
                    x.FirstAccepteDate, x.SecandAccepteDate, x.ThirdAceepteDate,
                    x.DeclareDate, x.OpnTechDate, x.SetTechDate , x.OpnFinDate , x.SetFinDate });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbfixprolistdef()
        {
            var query = db.ProList.Where(z => z.IsActive == true && z.Posted == 3 && z.ProStop == false)
                .Select(x => new {
                    x.ID,
                    x.ProName,
                    x.TotalVal,
                    x.FirstAccepteDate,
                    x.SecandAccepteDate,
                    x.ThirdAceepteDate,
                    x.DeclareDate,
                    x.OpnTechDate,
                    x.SetTechDate,
                    x.OpnFinDate,
                    x.SetFinDate,
                    x.ProNum,
                    x.ProDate,
                    x.ProVal
                });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbpurprolistdef()
        {
            var query = db.ProList.Where(z => z.IsActive == true && z.Posted == 3 && z.ProStop == false)
                .Select(x => new {
                    x.ID,
                    x.ProName,
                    x.Company.CompanyName,
                    x.PurType.PurName,
                    x.ProNum,
                    x.ProDate,
                    x.ProVal,
                    x.StartDate,
                    x.EndDate,
                    x.DurDateFirst,
                    x.DurDateSec,
                    x.DurDateThird
                });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbrpsixdef()
        {
            var query = db.ProList.Where(z => z.IsActive == true )
                .Select(x => new {
                    x.ID,
                    x.ProName,
                    x.TotalVal,
                    x.FirstAccepteDate,
                    x.SecandAccepteDate,
                    x.ThirdAceepteDate,
                    x.DeclareDate,
                    x.OpnTechDate,
                    x.SetTechDate,
                    x.OpnFinDate,
                    x.SetFinDate,
                    x.ProNum,
                    x.ProDate,
                    x.ProVal,
                    x.PostList.PostedName
                });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbprolistvdef(int? id)
        {
            var query = db.ProList.Where(x => x.IsActive && x.ComFK == id)
                .Select(x => new { x.ID, x.ProName, x.KPro.KName, x.ProNum, x.ProDate });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbpurdef()
        {
            var query = db.PurType.Where(z => z.IsActive == true)
                .Select(p => new { p.ID, p.PurName });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbKProdef(int? id)
        {

            var query = db.KPro.Where(z => z.TProFK == id && z.IsActive == true)
            .Select(p => new { p.ID, p.KName });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbgalary(int? id)
        {

            var query = db.ArchPro
            .Select(p => new { p.ID, p.ProList.ProName , p.ReNamePic,p.Photo });
            return Json(new { aaData = query }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult tbactivitydef()
        {
            ErpDB db = new ErpDB();
            var query = db.CActivity.Where(z => z.IsActive == true)

ERP/Views/Shared/Acc.cshtml
<!DOCTYPE html>
<html lang="ar-EG">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Assets/favicon.ico">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/Assets")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/ERP/Admin/Index">الرئيسية</a></li>
                    <li class="active"><a href="/ERP/Admin/cash"></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right flip">
                    <li>
                        <a class="label-danger" href="/ERP/Home/LogOut">
                            <i class="glyphicon glyphicon-log-out"></i>
                        </a>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/wAssets")
    @RenderSection("scripts", required: false)
</body>
</html>

ERP/Views/Shared/Admin.cshtml
<!DOCTYPE html>
<html lang="ar-eg">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Assets/favicon.ico">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top glyphicon-text-height" >
        <div class="container">
            @*<div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>*@
            <ul class="nav navbar-nav">
                <li class="active"><a href="/ERP/Admin/Index">الرئيسية</a></li>
                <li class="active"><a href="/ERP/Admin/cash"></a></li>
                @*<li class="active" id="cashrp"><a href="javascript:;">تقرير مبيعات يومي</a></li>
                <li class="active" id="bbordday"><a  href="javascript:;">تعديل طلب </a></li>
                <li class="active" id="bbexplist"><a href="javascript:;"> دليل المصروفات</a></li>
                <li class="active" id="topten"><a href="javascript:;">Top 10 AG</a></li>
                <li class="active" id="toptenfd"><a href="javascript:;">Top 10 FD</a></li>
                <li class="active"><a href="/ERP/User/Index">UseAdmin</a></li>*@
                @*<li class="active"><a href="/Meno/Finance/Finance">الحسابات</a></li>
    <li class="active"><a href="/Meno/HR/Index">شئون العاملين</a></li>
    <li class="active"><a href="/Meno/InvMan/Index">المخازن</a></li>*@
            </ul>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right flip">
                    <li>
                        <a class="label-danger" href="/ERP/Home/LogOut">
                            <i class="glyphicon glyphicon-log-out"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @RenderSection("scripts", required: false)
</body>
</html>

ERP/Views/Shared/AppLayout.cshtml
<!DOCTYPE html>
<html lang="ar-eg">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Assets/favicon.ico">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/Assets")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
       </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/ERP/Casher/Index">كاشير</a></li>    
                </ul>
                <ul class="nav navbar-nav navbar-right flip">
                    <li>
                        <a class="label-danger" href="/ERP/Home/LogOut">
                            <i class="glyphicon glyphicon-log-out"></i>
                        </a>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/wAssets")
    @RenderSection("scripts", required: false)
</body>
</html>

ERP/Views/Shared/Cash.cshtml
<!DOCTYPE html>
<html lang="ar-EG">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Assets/favicon.ico">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/Assets")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li class="active"><a href="/ERP/Admin/Index">الرئيسية</a></li>
                    <li class="active"><a href="/ERP/Rec/RecAdmin">مدير النظام</a></li>
                    <li class="active"><a href="/ERP/Finance/Index">الحسابات</a></li>
                    <li class="active"><a href="/ERP/HR/Index">شئون العاملين</a></li>
                    <li class="active"><a href="/ERP/InvMan/Index">المخازن</a></li>*@
                </ul>
                <ul class="nav navbar-nav navbar-right flip">
                    <li>
                        <a class="label-danger" href="/ERP/Home/LogOut">
                            <i class="glyphicon glyphicon-log-out"></i>
                        </a>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container body-content">
        @*<nav>
            <ul class="nav nav-justified nav-fixed-top">
                <li class="dropdown"><a herf="#" class="dropdown-toggle" role="button" data-toggle="dropdown" >حسابات عامة <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href='@Url.Action("AccTree", "Finance")'>دليل الحسابات</a></li><li class="divider"></li>
                        <li><a href='@Url.Action("Per", "Finance")'>الفترات المالية</a></li><li class="divider"></li>
                        <li><a href='@Url.Action("JEntry", "Finance")'>قيود اليومية</a></li>
                    </ul>
                </li>
                <li class="dropdown"><a herf="#" class="dropdown-toggle" role="button" data-toggle="dropdown">النقدية <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href='@Url.Action("CashIndex", "Finance")'>حركة الخزينة</a></li><li class="divider"></li>
                        <li><a href='@Url.Action("Bank", "Finance")'>البنك</a></li><li class="divider"></li>
                        <li><a href='@Url.Action("Cashtrans", "Finance")'>تحويلات</a></li><li class="divider"></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a herf="#" class="dropdown-toggle" role="button" data-toggle="dropdown">المساهمين <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href='@Url.Action("GetHolds", "Shar")'>المساهمين</a></li>
                        <li><a href='@Url.Action("Getshrs", "Shar")'>الأسهم</a></li>
                        <li><a href='@Url.Action("GetAccSh", "Shar")'>حسابات المساهمين</a></li>
                    </ul>
                </li>
                <li><a href='@Url.Action("CostCenter", "Finance")'>التكاليف</a></li>
                <li class="dropdown">
                    <a herf="#" class="dropdown-toggle" role="button" data-toggle="dropdown">الموردين <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href='@Url.Action("GetVendors", "Shar")'>قائمة الموردين</a></li>
                        <li><a href='@Url.Action("Vendors", "Shar")'>مجموعات الموردين</a></li>
                        <li><a href='@Url.Action("GetAccVen", "Shar")'>حـ/ الموردين</a></li>
                    </ul>
                </li>
                <li><a href='@Url.Action("Mor", "HR")'>الأصول الثابتة</a></li>
                <li><a href='@Url.Action("Pun", "HR")'>التعاقدات</a></li>
            </ul>
        </nav>*@
        <br />
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @RenderSection("scripts", required: false)
</body>
</html>

ERP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ar-eg">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Assets/favicon.ico">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jquery-ui")
@RenderSection("scripts", required: false)
</body>
</html>

ERP/Views/Shared/_Pro.cshtml
<!DOCTYPE html>
<html lang="ar-EG">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Assets/favicon.ico">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li class="active"><a href="/Erp/User/AboutMe">About Me</a></li>*@
                    <li class="active"><a href="/Erp/Pro/Index">الرئيسية</a></li>
                    <li class="active"><a href="/ERP/User/Index">مدير النظام</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right flip">
                    <li>
                        <a class="label-danger" href="/Erp/Home/LogOut">
                            <i class="glyphicon glyphicon-log-out"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <nav>
        <ul class="nav nav-justified nav-fixed-top">
            <li class="dropdown">
                <a herf="#" class="dropdown-toggle" role="button" data-toggle="dropdown">الشركات <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href='@Url.Action("Cpy", "Pro")'>قائمة الشركات</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("Garch", "Pro")'>أرشيف الصور</a></li>
                    <li class="divider"></li>
                </ul>
            </li>
            <li class="dropdown">
                <a herf="#" class="dropdown-toggle" role="button" data-toggle="dropdown">المشروعات <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href='@Url.Action("Prolist", "Pro")'>تصنيف المشروعات</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("AdPro", "Pro")'> طرح مشروع</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("TechPro", "Pro")'> الفتح الفنى</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("FinPro", "Pro")'> الفتح المالي</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("FixPro", "Pro")'> الاسناد</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("DurPro", "Pro")'> اضافة مدة</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("OverPro", "Pro")'> تجاوز مالي</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a herf="#" class="dropdown-toggle" role="button" data-toggle="dropdown">نماذج تقارير <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href='@Url.Action("RPsix", "Pro")'>نموذج 6</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("RPseven", "Pro")'>نموذج 7</a></li>
                    <li class="divider"></li>
                    <li><a href='@Url.Action("DonePro", "Pro")'> اداء المشروعات</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @RenderSection("scripts", required: false)
</body>
</html>

ERP/Views/Shared/_opr.cshtml
<!DOCTYPE html>
<html lang="ar-eg">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Assets/favicon.ico">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/Assets")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right flip">
                    <li>
                        <a class="label-danger" href="/ERP/Home/LogOut">
                            <i class="glyphicon glyphicon-log-out"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
            <nav>
                <ul class="nav nav-justified nav-fixed-top">
                    <li><a href='@Url.Action("Index", "Opr")'>الرئيسية</a></li>
                    <li><a href='@Url.Action("adopr", "Opr")'>اضافة</a></li>
                    <li><a href='@Url.Action("arcopr", "Opr")'>أرشيف</a></li>
                    <li><a href='@Url.Action("Graph", "Opr")'>رسم بيانى</a></li>
                </ul>
            </nav>
            <br />
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/wAssets")
    @RenderSection("scripts", required: false)
</body>
</html>